### ISSUE TITLE
Onboard user LED is always on

### ISSUE THREAD

**Issue by ThreepE0** [spark/InternetButton#11]
When using this library, I can't find a way to shut down the tiny onboard blue LED (not the pulsing status LED, I've got that one turned off no problem) without breaking the functionality of the buttons.  Am I missing something, or is it just not possible?

**Comment by joerocklin** [comment]
If you look at the library code, they've got all of the physical buttons connected with [internal pull-up resistors](https://github.com/spark/InternetButton/blob/6598932150065e3afb43005509f6dba10eccea1b/firmware/InternetButton.cpp#L28) and[ button 4 is attached to pin 7](https://github.com/spark/InternetButton/blob/6598932150065e3afb43005509f6dba10eccea1b/firmware/InternetButton.cpp#L10), which is where the onboard LED is connected. So in the 'normal' state the LED will be on because of the pull-up resistor.

You can override this and set pin 7 to low and turn off the LED, but that essentially means that button 4 is always going to be in a 'pushed' state. That may or may not matter for your application (don't try to use the `allButtonsOff` method).
